# Generated by Django 5.0.3 on 2024-05-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passChange',
            field=models.BooleanField(default=False),
        ),
    ]
