# Generated by Django 5.0.4 on 2024-05-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
