# Generated by Django 5.0.4 on 2024-05-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
