# Generated by Django 5.0.3 on 2024-05-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_passchange'),
        ('app', '0004_customuser_apellido_customuser_mail_and_more'),
    ]

    operations = [
    ]
