# Generated by Django 5.0.4 on 2024-05-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20240519_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='filial',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('usuario', 'Usuario intercambiador'), ('admin', 'Administrador'), ('ayudante', 'Usuario ayudante')], default='usuario', max_length=8),
        ),
    ]
