# Generated by Django 5.0.6 on 2024-05-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customuser_filial_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fechaNacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
