# Generated by Django 5.0.6 on 2024-05-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customuser_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.IntegerField(default=0, max_length=20, unique=True),
        ),
    ]
