# Generated by Django 5.0.6 on 2024-05-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customuser_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('usuario', 'Usuario intercambiador'), ('admin', 'Administrador'), ('ayudante', 'Usuario ayudante')], default='admin', max_length=8),
        ),
    ]
