# Generated by Django 5.0.6 on 2024-06-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customuser_is_blocked_customuser_pendiente_bloqueo'),
        ('app', '0010_remove_customuser_filial'),
    ]

    operations = [
    ]
