# Generated by Django 5.0.4 on 2024-06-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customuser_is_blocked_customuser_pendiente_bloqueo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pendiente_bloqueo',
        ),
    ]
