# Generated by Django 5.0.4 on 2024-06-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customuser_motivo_bloqueo'),
        ('app', '0012_customuser_is_blocked_customuser_pendiente_bloqueo'),
    ]

    operations = [
    ]
