# Generated by Django 5.0.3 on 2024-06-08 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20240605_1904'),
        ('app', '0014_customuser_failed_login_attempts'),
    ]

    operations = [
    ]
