# Generated by Django 5.0.6 on 2024-06-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20240610_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='solicitudes_pendientes_enviadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='solicitudes_pendientes_recibidas',
            field=models.IntegerField(default=0),
        ),
    ]
