# Generated by Django 5.0.3 on 2024-06-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20240608_2306'),
        ('app', '0015_merge_20240610_1651'),
    ]

    operations = [
    ]
