# Generated by Django 5.0.4 on 2024-06-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20240610_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cantidad_rechazos_publicacion',
            field=models.IntegerField(default=0),
        ),
    ]
