# Generated by Django 5.0.4 on 2024-06-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_customuser_solicitudes_pendientes_enviadas_and_more'),
        ('app', '0017_customuser_cantidad_rechazos_publicacion'),
    ]

    operations = [
    ]
