# Generated by Django 5.0.4 on 2024-06-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge_20240612_1442'),
        ('app', '0018_merge_20240612_1522'),
    ]

    operations = [
    ]
