# Generated by Django 5.0.3 on 2024-06-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20240619_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='puntaje',
            field=models.IntegerField(default=3),
        ),
    ]
