# Generated by Django 4.2.11 on 2024-07-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_customuser_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='puntaje',
            field=models.FloatField(default=3.0),
        ),
    ]
