# Generated by Django 5.0.6 on 2024-06-11 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargarArticulo', '0004_alter_articulo_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Articulo Pendiente'), ('Aprobado', 'Articulo Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('articulo_ofrecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_donde_es_ofrecido', to='cargarArticulo.articulo')),
                ('articulo_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_donde_es_solicitado', to='cargarArticulo.articulo')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Intercambios',
            },
        ),
    ]
