# Generated by Django 5.0.6 on 2024-06-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitarIntercambio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='codigo_intercambio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='intercambio',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
