# Generated by Django 5.0.6 on 2024-06-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitarIntercambio', '0002_intercambio_codigo_intercambio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intercambio',
            old_name='codigo_intercambio',
            new_name='codigo_intercambio_destinatario',
        ),
        migrations.AddField(
            model_name='intercambio',
            name='codigo_intercambio_solicitante',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
