# Generated by Django 5.0.3 on 2024-07-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitarIntercambio', '0005_intercambio_codigo_intercambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='reseña_destinatario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intercambio',
            name='reseña_solicitante',
            field=models.BooleanField(default=False),
        ),
    ]
