# Generated by Django 4.2.11 on 2024-07-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitarIntercambio', '0005_intercambio_codigo_intercambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Articulo Pendiente'), ('Aceptado', 'Articulo Aceptado'), ('Rechazado', 'Rechazado'), ('Efectuado', 'Efectuado'), ('No efectuado', 'No efectuado')], default='Pendiente', max_length=20),
        ),
    ]
