# Generated by Django 4.2.11 on 2024-07-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitarIntercambio', '0006_alter_intercambio_estado'),
        ('solicitarIntercambio', '0006_intercambio_reseña_destinatario_and_more'),
    ]

    operations = [
    ]
