# Generated by Django 5.0.3 on 2024-06-30 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reseñado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('reseñante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_dejadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
