# Generated by Django 5.0.6 on 2024-05-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crearFilial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='ayudante',
        ),
    ]
