# Generated by Django 5.0.6 on 2024-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crearFilial', '0003_filial_ayudante'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='turnos',
            field=models.JSONField(default=list),
        ),
    ]
