# Generated by Django 5.0.4 on 2024-06-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crearFilial', '0005_alter_filial_ayudante'),
        ('crearFilial', '0005_remove_filial_turnos_turno'),
    ]

    operations = [
    ]
