# Generated by Django 5.0.4 on 2024-06-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crearFilial', '0006_merge_20240612_1522'),
        ('crearFilial', '0007_alter_filial_ayudante'),
    ]

    operations = [
    ]
