# Generated by Django 4.2.11 on 2024-07-02 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crearFilial', '0009_filial_latitud_filial_longitud_alter_filial_ayudante'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filial',
            name='ayudante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
