# Generated by Django 5.0.4 on 2024-05-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarAyudante', '0002_alter_customuser_fecha_nacimiento_and_more'),
        ('registrarAyudante', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
    ]
