# Generated by Django 5.0.3 on 2024-05-22 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crearFilial', '0001_initial'),
        ('registrarAyudante', '0003_merge_20240520_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='filial',
        ),
        migrations.AddField(
            model_name='customuser',
            name='ffilial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crearFilial.filial'),
        ),
    ]
