# Generated by Django 5.0.3 on 2024-05-22 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarAyudante', '0004_remove_customuser_filial_customuser_ffilial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ffilial',
            new_name='filial',
        ),
    ]
