# Generated by Django 5.0.6 on 2024-05-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarAyudante', '0005_rename_ffilial_customuser_filial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
