# Generated by Django 5.0.4 on 2024-05-12 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargarArticulo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='categoria',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='descripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='estado',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='foto',
            new_name='Foto',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='titulo',
            new_name='Titulo',
        ),
    ]
