# Generated by Django 4.2.11 on 2024-07-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargarArticulo', '0005_articulo_motivo_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
    ]
